USE bench;

CREATE TABLE IF NOT EXISTS books (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    author INT NOT NULL,
    price DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS authors (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userid INT NOT NULL,
    name VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(512) NOT NULL,
    review TEXT NOT NULL,
    rating DECIMAL NOT NULL,
    book INT NOT NULL,
    user INT NOT NULL
);

INSERT IGNORE INTO users (name) VALUES ('Anon');
INSERT IGNORE INTO authors (name) VALUES ('Mr. Anon');
INSERT IGNORE INTO books (name, author, price) VALUES ('Anon', 1, 4.2);
